version: "3.8"

services:
  database:
    image: postgres:15
    container_name: bitbridge-database
    environment:
      POSTGRES_USER: "bitbridge"
      POSTGRES_PASSWORD: "bitbridgepass"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
    networks:
      - kong-net

  kong-migration:
    image: kong/kong-gateway:3.11.0.1
    container_name: kong-migration
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "bitbridge-database"
      KONG_PG_USER: "bitbridge"
      KONG_PG_PASSWORD: "bitbridgepass"
      KONG_PASSWORD: "kongadminpassword"
    networks:
      - kong-net
    entrypoint: ["/bin/sh", "-c", "kong migrations bootstrap"]
    depends_on:
      - database
    restart: on-failure

  kong-gateway:
    image: kong/kong-gateway:3.11.0.1
    container_name: kong-gateway
    environment:
      KONG_ROUTER_FLAVOR: "expressions"
      KONG_WORKER_CONSISTENCY: "eventual"
      KONG_ROUTER_CONSISTENCY: "eventual"
      KONG_NGINX_WORKER_CONNECTIONS: "512"
      KONG_DATABASE: "postgres"
      KONG_REAL_IP_RECURSIVE: "on"
      KONG_TRUSTED_IPS: "0.0.0.0/0,::/0"
      KONG_PG_HOST: "bitbridge-database"
      KONG_PG_USER: "bitbridge"
      KONG_PG_PASSWORD: "bitbridgepass"
      KONG_NGINX_WORKER_PROCESSES: "1"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_GUI_URL: "http://localhost:8002"
      KONG_PASSWORD: "kongadminpassword"
    ports:
      - "80:8000"
      - "8000:8000"
      - "8443:8443"
      - "443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    extra_hosts: 
      - "host.docker.internal:host-gateway"
    networks:
      - kong-net
    restart: always
    depends_on:
      - database
      - kong-migration

  etcd:
    image: quay.io/coreos/etcd:v3.5.25
    container_name: etcd
    environment:
      ETCD_NAME: "etcd0"
      ETCD_INITIAL_CLUSTER: "etcd0=http://0.0.0.0:2380"
      ETCD_INITIAL_CLUSTER_STATE: "new"
      ETCD_INITIAL_CLUSTER_TOKEN: "etcd-cluster"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://0.0.0.0:2380"
    ports:
      - "2379:2379"
      - "2380:2380"
    restart: always

networks:
  kong-net:
    driver: bridge

volumes:
  postgres_data: