import { DM_Mono, Inter } from 'next/font/google';
import type { Metadata, Viewport } from "next";
import "./globals.css";
import localFont from 'next/font/local';
import CoreStart from "@/app/core_start";
import AppToaster from "@/components/ui/toaster";

const dmSans = localFont({
  src: [
    {
      path: '../fonts/dm-sans/DMSans-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/dm-sans/DMSans-Italic.ttf',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../fonts/dm-sans/DMSans-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../fonts/dm-sans/DMSans-MediumItalic.ttf',
      weight: '500',
      style: 'italic',
    },
    {
      path: '../fonts/dm-sans/DMSans-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../fonts/dm-sans/DMSans-SemiBoldItalic.ttf',
      weight: '600',
      style: 'italic',
    },
    {
      path: '../fonts/dm-sans/DMSans-BoldItalic.ttf',
      weight: '700',
      style: 'italic',
    },
  ],
  variable: '--font-dm-sans',
  display: 'swap',
});
const dmMono = DM_Mono({
  weight: ['400', '500'],
  subsets: ['latin'],
  variable: '--font-dm-mono',
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});
export const metadata: Metadata = {
  title: "Bytover",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/favicon16.ico", sizes: "16x16", type: "image/x-icon" },
      { url: "/favicon32.ico", sizes: "32x32", type: "image/x-icon" },
      { url: "/favicon64.ico", sizes: "64x64", type: "image/x-icon" },
      { url: "/favicon512.ico", sizes: "512x512", type: "image/x-icon" },
    ],
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={"w-full h-full"}>
        <body
          className={`w-full h-full min-h-screen ${dmSans.variable} ${dmMono.variable} ${inter.variable} antialiased dark`}>
        {children}
        <CoreStart/>
        <AppToaster />
      </body>
    </html>
  );
}
