/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const start_worker: () => void;
export const process_event: (a: any) => any;
export const handle_response: (a: number, b: any) => any;
export const view: () => any;
export const is_compatible: () => any;
export const init: () => any;
export const add_device_files: (a: any) => any;
export const add_device_folder: (a: number, b: number, c: number, d: number) => any;
export const get_device_file: (a: any) => any;
export const get_download_url: (a: any) => any;
export const execute_operation: (a: any) => any;
export const create_file: (a: any, b: any) => any;
export const execute: (a: number, b: any) => any;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const intounderlyingsource_cancel: (a: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_export_6: WebAssembly.Table;
export const closure7909_externref_shim: (a: number, b: number, c: any) => void;
export const closure7713_externref_shim: (a: number, b: number, c: any) => void;
export const closure276_externref_shim: (a: number, b: number, c: any) => void;
export const closure7710_externref_shim: (a: number, b: number, c: any) => void;
export const closure277_externref_shim: (a: number, b: number, c: any) => void;
export const closure7855_externref_shim: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__ha59ecba20431b6e7: (a: number, b: number) => void;
export const closure7711_externref_shim: (a: number, b: number, c: any) => void;
export const closure7712_externref_shim: (a: number, b: number, c: any) => void;
export const closure7856_externref_shim: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hb5e047f6458a2444: (a: number, b: number) => void;
export const closure8471_externref_shim: (a: number, b: number, c: any) => void;
export const closure8261_externref_shim: (a: number, b: number, c: any) => void;
export const closure8148_externref_shim: (a: number, b: number, c: any) => void;
export const closure7854_externref_shim: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hff34c56f5e583ff1: (a: number, b: number) => void;
export const closure8479_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
