version: "3.8"

services:
  relay-server:
    image: midwesshub/bytover-relay:${RELAY_SERVER_IMAGE_TAG:?set RELAY_SERVER_IMAGE_TAG to the short git SHA image tag}
    networks:
      - host
    environment:
      RELAY_SERVER_SECRET: ${RELAY_SERVER_SECRET:?set RELAY_SERVER_SECRET}
      BYTOVER_WITH_SSL: ${BYTOVER_WITH_SSL:-0}
      BYTOVER_PUBLIC_GATEWAY_HOST: ${BYTOVER_PUBLIC_GATEWAY_HOST:-localhost}
      BYTOVER_PUBLIC_GATEWAY_PORT: ${BYTOVER_PUBLIC_GATEWAY_PORT:-8000}
      BYTOVER_PUBLIC_HTTP1_GATEWAY_HOST: ${BYTOVER_PUBLIC_HTTP1_GATEWAY_HOST:-localhost}
      BYTOVER_PUBLIC_HTTP1_GATEWAY_PORT: ${BYTOVER_PUBLIC_HTTP1_GATEWAY_PORT:-8000}
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.platform.os == linux

networks:
  host:
    external: true
    name: host
