/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const start_worker: () => void;
export const process_event: (a: any) => any;
export const handle_response: (a: number, b: any) => any;
export const view: () => any;
export const init: () => any;
export const add_device_files: (a: any) => any;
export const get_device_file: (a: bigint) => any;
export const load_thumbnail_bytes: (a: bigint) => any;
export const load_thumbnail_source: (a: any) => any;
export const download_file_from_cache: (a: any, b: any) => any;
export const execute: (a: number, b: any) => any;
export const is_compatible: () => any;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const intounderlyingsource_cancel: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_1: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_export_6: WebAssembly.Table;
export const closure113_externref_shim: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h933ca4df983b9f21: (a: number, b: number) => void;
export const closure6705_externref_shim: (a: number, b: number, c: any) => void;
export const closure6712_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
