/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const start_worker: () => void;
export const process_event: (a: any) => any;
export const handle_response: (a: number, b: any) => any;
export const view: () => any;
export const __wbg_nativeprocessor_free: (a: number, b: number) => void;
export const nativeprocessor_is_compatible: () => any;
export const nativeprocessor_init: () => any;
export const nativeprocessor_add_device_files: (a: number, b: any) => any;
export const nativeprocessor_get_device_file: (a: number, b: bigint) => any;
export const nativeprocessor_load_thumbnail_bytes: (a: number, b: bigint) => any;
export const nativeprocessor_load_thumbnail_source: (a: number, b: number, c: number) => any;
export const nativeprocessor_download_file_from_cache: (a: number, b: number, c: number, d: any) => any;
export const nativeprocessor_execute: (a: number, b: number, c: any) => any;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const intounderlyingsource_cancel: (a: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_export_6: WebAssembly.Table;
export const closure313_externref_shim: (a: number, b: number, c: any) => void;
export const closure314_externref_shim: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h4190fd15aa7955cc: (a: number, b: number) => void;
export const closure9723_externref_shim: (a: number, b: number, c: any) => void;
export const closure9720_externref_shim: (a: number, b: number, c: any) => void;
export const closure9721_externref_shim: (a: number, b: number, c: any) => void;
export const closure9722_externref_shim: (a: number, b: number, c: any) => void;
export const closure9865_externref_shim: (a: number, b: number, c: any) => void;
export const closure9866_externref_shim: (a: number, b: number, c: any) => void;
export const closure9864_externref_shim: (a: number, b: number, c: any) => void;
export const closure9915_externref_shim: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h57e2ffa9d5864f11: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h933ca4df983b9f21: (a: number, b: number) => void;
export const closure10240_externref_shim: (a: number, b: number, c: any) => void;
export const closure10389_externref_shim: (a: number, b: number, c: any) => void;
export const closure10396_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
