name: Railway Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo '${{ secrets.SSH_PRIVATE_KEY }}'
      - name: Deploy to Railway
        uses: Midwess/deployment/.github/actions/railway_deployment@main
        with:
          version: ${{ github.sha }}
          submodules: 'libs/schema,libs/devlog-sdk,libs/core-services'
          repository: 'Midwess/Bytover'
          deploy_branch: ${{ github.ref_name == 'production' && 'deploy-production' || 'deploy' }}
          ssh_key: ${{ vars.SSH_PRIVATE_KEY }}